CREATE DATABASE SESI;
use sesi ;


/* -- TABELAS GESTOR -- */

CREATE TABLE GESTOR_ADMINS (
IDADMIN INT(4) PRIMARY KEY auto_increment,
NOME VARCHAR(50),
CPF CHAR(11),
EMAIL VARCHAR(50),
SENHA VARCHAR(30),
SEXO ENUM("M","F","PREFIRO NÃO INFORMAR"),
CARGO VARCHAR(30)

/* CHAVE ESTRANGEIRA*/

);

CREATE TABLE GESTORES (
IDGESTOR INT (4) PRIMARY KEY auto_increment,
NOME VARCHAR(50),
CPF CHAR(11),
SENHA VARCHAR(30),
EMAIL VARCHAR(50),
SEXO ENUM("M","F","PREFIRO NÃO INFORMAR"),
CARGO VARCHAR(30),

/* CHAVE ESTRANGEIRA*/
ID_ADMIN INT(4),
FOREIGN KEY (ID_ADMIN)
references GESTOR_ADMINS (IDADMIN)
);


/* -- TABELAS MEDICO -- */
CREATE TABLE MEDICOS (
IDMEDICO INT(4) PRIMARY KEY auto_increment,
NOME VARCHAR(50),
CPF CHAR(11),
CRM CHAR(13),
SEXO ENUM("M","F","PREFIRO NÃO INFORMAR"),
EMAIL VARCHAR(50),
SENHA VARCHAR(30),
ESPECIALIDADE VARCHAR(35),
CARGO VARCHAR (30),

/* CHAVE ESTRANGEIRA*/
ID_GESTOR_MED INT(4),
FOREIGN KEY (ID_GESTOR_MED) 
references GESTORES (IDGESTOR)

);

CREATE TABLE END_MEDS (
IDEND_MED INT(4) PRIMARY KEY auto_increment,
CEP CHAR(8),
LOGRADOURO VARCHAR(100),
NUM_END_MED varchar(7),
BAIRRO VARCHAR(50),
COMPLEMENTO VARCHAR(50),
PT_REF VARCHAR(50),
CIDADE VARCHAR(50),
UF CHAR(2),
PAIS VARCHAR(30),
TIPO_END_MED ENUM ('RESIDENCIAL', 'COMERCIAL'),

/* CHAVE ESTRANGEIRA*/								
ID_END_MED INT(4),
FOREIGN KEY (ID_END_MED) 
references MEDICOS (IDMEDICO)
);

CREATE TABLE TEL_MEDS (
IDTEL_MED INT(4) PRIMARY KEY auto_increment,
DDD CHAR(2),
NUM_TEL_MED VARCHAR(9),
TIPO_TEL_MED ENUM('RESIDENCIAL', 'COMERCIAL','CELULAR'),

/* CHAVE ESTRANGEIRA*/
ID_TEL_MED INT(4),
FOREIGN KEY (ID_TEL_MED) 
references MEDICOS (IDMEDICO)
);
/* -- TABELAS MEDICO -- */


/* -- TABELAS ATLETA -- */
CREATE TABLE ATLETAS (
IDATLETA INT(4) PRIMARY KEY auto_increment,
NOME VARCHAR(100),
CPF CHAR(11),
EMAIL varchar(50),
SENHA VARCHAR(30),
D_NASC DATE,
SEXO ENUM('F','M','PREFIRO NÃO INFORMAR'),
CATEGORIA VARCHAR(30),
CARGO VARCHAR(20),
MODALIDADE VARCHAR(30),
SOLICITACAO ENUM("SOLICITADO","NÃO SOLICITADO"),
SITUACAO enum("APROVADO","PENDENTE","REPROVADO"),

/* CHAVE ESTRANGEIRA 1,N */
ID_GESTOR_ATL INT(4),
FOREIGN KEY (ID_GESTOR_ATL) 
references GESTORES (IDGESTOR)
);

CREATE TABLE END_ATLS (
IDEND_ATL INT(4) PRIMARY KEY auto_increment,
CEP CHAR(8),
LOGRADOURO VARCHAR(100),
NUM_END_ATL varchar(7),
BAIRRO VARCHAR(100),
COMPLEMENTO VARCHAR(50),
PT_REF VARCHAR(50),
CIDADE VARCHAR(60),
UF CHAR(2),
PAIS VARCHAR(30),
TIPO_END_ATL ENUM ('RESIDENCIAL', 'COMERCIAL'),

ID_END_ATL INT(4),
FOREIGN KEY (ID_END_ATL) 
references ATLETAS (IDATLETA)
);

CREATE TABLE TEL_ATLS (
IDTEL_ATL INT(4) PRIMARY KEY auto_increment,
DDD CHAR(2),
NUM_TEL_ATL VARCHAR(9),
TIPO_TEL_ATL ENUM('RESIDENCIAL', 'COMERCIAL','CELULAR'),

ID_TEL_ATL INT(4),
FOREIGN KEY (ID_TEL_ATL) 
references ATLETAS (IDATLETA)
);
/* -- TABELAS ATLETA -- */


/* -- TABELAS EXAME -- */
CREATE TABLE EXAMES (
IDEXAME INT(4) PRIMARY KEY auto_increment,
TIPO VARCHAR(100),
DESCRIÇÃO TEXT,
DATA_EX DATETIME,
SITUACAO ENUM("CONCLUIDO","ANALISE","PENDENTE"),
OBSERVACAO TEXT,

/* CHAVE ESTRANGEIRA*/
ID_EXAME_ATL INT(4),
FOREIGN KEY (ID_EXAME_ATL) 
references ATLETAS (IDATLETA),

ID_EXAME_MED INT(4),
FOREIGN KEY (ID_EXAME_MED) 
references MEDICOS (IDMEDICO)
);
/* -- TABELAS EXAME -- */


/* TABELAS MEDICO CONVIDADO*/
CREATE TABLE MED_CONVS (
ID_MED_CONV INT(4) PRIMARY KEY auto_increment,
NOME VARCHAR(50),
CPF CHAR(11),
ESPECIALIDADE VARCHAR(30),
EMAIL VARCHAR(100),
SENHA VARCHAR(30),
CRM CHAR(13),
SEXO ENUM("M","F","PREFIRO NÃO INFORMAR"),
CARGO VARCHAR(30),

/* CHAVE ESTRANGEIRA*/
ID_GEST_CONV INT(4),
FOREIGN KEY (ID_GEST_CONV) 
references GESTORES (IDGESTOR),

ID_EXAME_CONV INT(4),
FOREIGN KEY (ID_EXAME_CONV) 
references EXAMES (IDEXAME)
);

CREATE TABLE END_MED_CONVS (
ID_END_MED_CONV INT(4) PRIMARY KEY auto_increment,
CEP CHAR(8),
LOGRADOURO VARCHAR(100),
NUM_END_MED_CONV varchar(7),
BAIRRO VARCHAR(100),
COMPLEMENTO VARCHAR(50),
PT_REF VARCHAR(50),
CIDADE VARCHAR(60),
UF CHAR(2),
PAIS VARCHAR(30),
TIPO_END_MED_CONV ENUM ('RESIDENCIAL', 'COMERCIAL'),

/* CHAVE ESTRANGEIRA*/
ID_END_CONV INT(4),
FOREIGN KEY (ID_END_CONV) 
references MED_CONVS (ID_MED_CONV)
);

CREATE TABLE TEL_MED_CONVS (
IDTEL_MED_CONV INT(4) PRIMARY KEY auto_increment,
DDD CHAR(2),
NUM_TEL_MED_CONV VARCHAR(9),
TIPO_TEL_MED_CONV ENUM('RESIDENCIAL', 'COMERCIAL','CELULAR'),

/* CHAVE ESTRANGEIRA*/
ID_TEL_CONV INT(4),
FOREIGN KEY (ID_TEL_CONV) 
references MED_CONVS (ID_MED_CONV)
);






